apiVersion: apps/v1
kind: Deployment
metadata:
   name: caps2
   labels:
     apps: nginx
spec:
   replicas: 3
   selector:
      matchLabels:
         app: nginx
   template:
      metadata:
      labels:
         app: nginx
      spec:
         containers:
         - name: nginx
           image: kunjsaini445/nginx
           ports:
           - containerPort: 80
